import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { contactConfig } from "@/config/contact";
import Link from "next/link";
export default function ContactPage() {
    const email = "vaibhavkesarwani100@email.com";
    return (_jsxs("main", { className: "px-4 sm:px-6 py-8 sm:py-10", children: [_jsx("div", { className: "mb-12 sm:mb-14 flex justify-center", children: _jsxs("div", { className: "\n            w-full max-w-2xl\n            rounded-2xl sm:rounded-3xl\n            border border-black/10 dark:border-white/10\n            bg-white/40 dark:bg-white/2\n            backdrop-blur-2xl\n            shadow-xl\n            p-5 sm:p-8 md:p-10\n            space-y-4 sm:space-y-5\n          ", children: [_jsx("div", { className: "text-xs sm:text-sm font-bold uppercase tracking-wide", children: "Contact Information" }), contactConfig.socialData.map((data, i) => {
                            const Icon = data.icon;
                            return (_jsx(Link, { href: `mailto:${email}`, className: "\n              group block\n              rounded-xl sm:rounded-2xl\n              border border-black/10 dark:border-white/5\n              bg-white/60 dark:bg-white/5\n              backdrop-blur-xl\n              p-4 sm:p-5\n              transition-all duration-300 sm:duration-500\n              active:scale-[0.98]\n              sm:hover:scale-[1.015]\n              hover:border-black/30 dark:hover:border-white/30\n              hover:shadow-lg\n            ", children: _jsxs("div", { className: "flex items-center gap-4 sm:gap-5", children: [_jsx("div", { className: "\n                  p-2.5 sm:p-3\n                  rounded-lg sm:rounded-xl\n                  border border-black/10 dark:border-white/10\n                  bg-blue-300 dark:bg-yellow-300 dark:text-black\n                  transition-all duration-300\n                  sm:group-hover:scale-110\n                ", children: _jsx(Icon, { size: 18, className: "sm:stroke-[2.5]" }) }), _jsxs("div", { className: "min-w-0", children: [_jsx("p", { className: "text-[10px] sm:text-xs uppercase tracking-wider text-neutral-500", children: data.name }), _jsx("p", { className: "text-sm sm:text-lg md:text-xl font-semibold break-all", children: data.text })] })] }) }, i));
                        })] }) }), _jsxs("div", { className: "space-y-8 sm:space-y-10", children: [_jsx("h2", { className: "text-center text-lg sm:text-xl font-medium tracking-wide", children: "Find Me On" }), _jsx("div", { className: "\n            grid\n            grid-cols-2\n            lg:grid-cols-4\n            gap-4 sm:gap-6 lg:gap-8\n          ", children: contactConfig.socialLinks.map((social, i) => {
                            const Icon = social.icon;
                            return (_jsx(Link, { href: social.href, target: "_blank", className: "\n                  group relative\n                  rounded-2xl sm:rounded-3xl\n                  border border-black/10 dark:border-white/10\n                  backdrop-blur-xl\n                  p-5 sm:p-7 lg:p-8\n                  transition-all duration-300 sm:duration-500\n                  active:scale-[0.97]\n                  sm:hover:-translate-y-2\n                  hover:border-black/30 dark:hover:border-white/30\n                ", style: {
                                    animationDelay: `${i * 80}ms`,
                                }, children: _jsxs("div", { className: "flex flex-col items-center text-center gap-4 sm:gap-5", children: [_jsx("div", { className: "\n                      p-4\n                      rounded-2xl\n                      border border-black/10 dark:border-white/10\n                      bg-blue-300 dark:bg-yellow-300 text-black\n                      transition duration-500\n                      sm:group-hover:scale-110\n                    ", children: _jsx(Icon, { size: 22, className: "sm:size-6.5" }) }), _jsx("p", { className: "text-xs sm:text-sm font-semibold tracking-wide opacity-80 group-hover:opacity-100 transition", children: social.name })] }) }, social.name));
                        }) })] })] }));
}
